# Generated by Django 6.0.2 on 2026-02-11 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount_per_member',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
            preserve_default=False,
        ),
    ]
