# Generated by Django 5.2.9 on 2026-03-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_amount_per_member_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
